hydra:
    run: # specify the working directory
      dir: ./outputs/ROCStories # ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S} #./outputs/exp1 # 
defaults:
    - task: ROCStories
    - hydra/job_logging: colorlog
    - hydra/hydra_logging: colorlog
    - training: ROCStories
    - model: roberta-tokenized-gpt2
    - text_gail: ROCStories
    - decode: default

# DailyDialog, CommonGEN, ROCStories
